import './globals.css';
import LoginNav from './login-nav';
export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body>
            <header>
               <LoginNav />
            </header>
            <main className="min-h-screen bg-background flex flex-col items-center">
               {children}
            </main>
         </body>
      </html>
   );
}
