export const teamTriCodes = [
   'ANA',
   'CBJ',
   'SEA',
   'UTA',
   'DET',
   'WPG',
   'NJD',
   'NYI',
   'NYR',
   'SJS',
   'BOS',
   'FLA',
   'TBL',
   'CHI',
   'PIT',
   'PHI',
   'CAR',
   'DAL',
   'LAK',
   'VAN',
   'TOR',
   'OTT',
   'BUF',
   'STL',
   'MIN',
   'EDM',
   'VGK',
   'NSH',
   'MTL',
   'COL',
   'WSH',
   'CGY',
];
export const teamMap = {
   ANA: 'Anaheim Ducks',
   UTA: 'Utah Hockey Club',
   BUF: 'Buffalo Sabres',
   BOS: 'Boston Bruins',
   CGY: 'Calgary Flames',
   CAR: 'Carolina Hurricanes',
   CHI: 'Chicago Blackhawks',
   CBJ: 'Columbus Blue Jackets',
   COL: 'Colorado Avalanche',
   DAL: 'Dallas Stars',
   DET: 'Detroit Red Wings',
   EDM: 'Edmonton Oilers',
   FLA: 'Florida Panthers',
   LAK: 'Los Angeles Kings',
   MIN: 'Minnesota Wild',
   MTL: 'Montréal Canadiens',
   NJD: 'New Jersey Devils',
   NSH: 'Nashville Predators',
   NYI: 'New York Islanders',
   NYR: 'New York Rangers',
   OTT: 'Ottawa Senators',
   PHI: 'Philadelphia Flyers',
   PIT: 'Pittsburgh Penguins',
   SEA: 'Seattle Kraken',
   SJS: 'San Jose Sharks',
   STL: 'St. Louis Blues',
   TBL: 'Tampa Bay Lightning',
   TOR: 'Toronto Maple Leafs',
   VAN: 'Vancouver Canucks',
   VGK: 'Vegas Golden Knights',
   WPG: 'Winnipeg Jets',
   WSH: 'Washington Capitals',
};

export const LeagueScoringMap: { [key: string]: string } = {
   assists: 'A',
   blocked: 'BLK',
   goals: 'G',
   hits: 'H',
   pim: 'PIM',
   plusMinus: '+/-',
   powerPlayAssists: 'PPA',
   powerPlayGoals: 'PPG',
   powerPlayPoints: 'PPP',
   shortHandedAssists: 'SHA',
   shortHandedGoals: 'SHG',
   shortHandedPoints: 'SHP',
   shots: 'S',
};

export const GoalieStatsMap: { [key: string]: string } = {
   wins: 'W',
   saves: 'S',
   goalsAgainst: 'GA',
   shutouts: 'SO',
};
